### ISSUE TITLE
3D_TM_Rename_table_based_on_column_label Changes ToDo

### ISSUE THREAD

**Issue by MrPWG** [MrPWG/WhereScape-3D#1]
- [ ] Add proper formatting options

- [ ] Include default name handling in case of no column with correct attribute type

- [ ] Add a check to ensure that a valid name has been set
